version: "3"
services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver2 
    ports:
      - "9394:9300"
    environment:
      - CSVSERVER_BORDER=Orange
      - CSVSERVER_PATH=/csvserver/inputdata/inputFile
    volumes:
      - ./inputFile:/csvserver/inputdata
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
